# Generated by Django 3.0.7 on 2020-06-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NII',
        ),
    ]
